import { db } from "./firebase";
import { collection, getDocs, doc, setDoc, getDoc } from "firebase/firestore";

export const fetchChatsByUserId = async (userId) => {
  const userRef = doc(db, "users", userId);  // Lấy document của người dùng
  const chatsRef = collection(userRef, "chats");  // Lấy subcollection "chats" của user

  const querySnapshot = await getDocs(chatsRef);

  const chats = [];
  querySnapshot.forEach((doc) => {
    const data = doc.data();
    chats.push({
      id: doc.id,
      title: data.title || "Untitled Chat",
      messages: data.messages || [],
      time: data.timeUpdate || new Date().toISOString(), // Thêm thời gian cập nhật
    });
  });

  // log(chats); // In ra danh sách các cuộc trò chuyện
  console.log("Chats:", chats); // In ra danh sách các cuộc trò chuyện

  return chats;
};

export const updateChat = async (userId, chatId, updatedChat) => {
  const userRef = doc(db, "users", userId);

  // Kiểm tra người dùng đã tồn tại chưa
  const userSnap = await getDoc(userRef);
  if (!userSnap.exists()) {
    console.error("User document does not exist.");
    return { success: false };
  }

  let chatRef;
  let autoGeneratedId = chatId;

  if (!chatId) {
    // Tạo document với ID tự động
    chatRef = doc(collection(userRef, "chats"));
    autoGeneratedId = chatRef.id; // Lấy ID được tạo tự động
  } else {
    chatRef = doc(userRef, "chats", chatId);
  }

  try {
    await setDoc(chatRef, updatedChat, { merge: true });
    return { success: true, chatId: autoGeneratedId, title: updatedChat.title };
  } catch (error) {
    console.error("Error updating chat:", error);
    return { success: false };
  }
};
